include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Formatting
    require_trailing_commas: true
    prefer_single_quotes: true
    
    # Code quality
    always_declare_return_types: true
    avoid_print: false
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Naming
    constant_identifier_names: true
    file_names: true